apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cashaddress
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cashaddress
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
